name: pandoc_filter_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - libffi=3.4.4
  - openssl=3.2.0
  - pandoc=3.1.3
  - pip=23.3.1
  - python=3.12.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - ucrt=10.0.22621.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - about-time==4.2.1
      - alive-progress==3.1.5
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - build==1.0.3
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - coverage==7.4.0
      - crcmod==1.7
      - cryptography==41.0.7
      - grapheme==0.6.0
      - httplib2==0.22.0
      - idna==3.6
      - iniconfig==2.0.0
      - jmespath==0.10.0
      - oauth2client==4.1.3
      - oss2==2.18.4
      - packaging==23.2
      - panflute==2.3.0
      - pluggy==1.3.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pytest==7.4.4
      - pytest-cov==4.1.0
      - pyyaml==6.0.1
      - requests==2.31.0
      - rsa==4.9
      - setuptools==69.0.3
      - six==1.16.0
      - soupsieve==2.5
      - typeguard==4.1.5
      - urllib3==2.1.0