name: pandoc_filter_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pandoc>=3.1 -c conda-forge
  - pip:
      - setuptools
      - build
      - pytest
      - pytest-cov
      - requests
      - typeguard
      - packaging
      - alive-progress
      - panflute
      - oss2
      - bs4
      - oauth2client
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    