name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: pandoc_filter_dev
          environment-file: ./scripts/etc/conda_env_dev_linux.yml
      - name: Build package
        shell: pwsh
        run: |
          python -m build
      - name: Publish package (release or prerelease)
        run: |
          pip install -i https://pypi.org/simple/ --pre -U pandoc-filter
          