name: Build and Deploy

on:
  release:
    types: [published]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: pandoc_filter_dev
          environment-file: ./scripts/etc/environment.yml
      - shell: pwsh
        run: |
          pip install -U twine
          python -m build
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
          