name: Build
on: 
  workflow_run:
    workflows: ["Local Test"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build
        shell: pwsh
        run: . ./scripts/build.ps1