name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
      - name: Configurations
        shell: pwsh
        run: . ./scripts/config.ps1
      - name: Build package
        shell: pwsh
        run: |
          conda activate pandoc_filter_dev
          python -m build
      - name: Publish package (release or prerelease)
        run: |
          pip install -i https://pypi.org/simple/ --pre -U pandoc-filter
          