name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build package
        shell: pwsh
        run: . ./scripts/build.ps1
      - name: Publish package (prerelease)
        if: ${{ github.event.release.prerelease }}
        run: |
          pip install -U twine
          twine upload dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} -r testpypi
      - name: Publish package (release)
        if: ${{ !github.event.release.prerelease }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/