name: Local Test
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  local_test:
    runs-on: ubuntu-latest
    name: Local Test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Local Test
        env:
          OSS_ENDPOINT_NAME: ${{ secrets.OSS_ENDPOINT_NAME }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        shell: pwsh
        run: . ./scripts/test.ps1
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}