name: Post Deploy Test

on:
  workflow_run:
    workflows: ["Build and Upload Python Package"]
    types:
      - completed

jobs:
  post_deploy_test:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: pandoc_filter_dev
          environment-file: ./scripts/etc/environment.yml
      - env:
          OSS_ENDPOINT_NAME: ${{ secrets.OSS_ENDPOINT_NAME }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        shell: pwsh
        run: |
          pip install -i https://pypi.org/simple/ --pre -U pandoc-filter
          $package_path = (pip show pandoc_filter) -match 'Location:' -replace 'Location:\s+')
          pytest (Get-Item "./tests").FullName --log-level=INFO --cov $Env:PYTHONPATH --cov-report=xml
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}