name: Test and Build
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test_and_build_job:
    runs-on: ubuntu-latest
    name: Test and Build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
      - name: config
        shell: pwsh
        run: . ./scripts/config.ps1
      - name: Local Test
        env:
          OSS_ENDPOINT_NAME: ${{ secrets.OSS_ENDPOINT_NAME }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        shell: pwsh
        run: . ./scripts/local_test.ps1
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Test
        shell: pwsh
        run: . ./scripts/build.ps1